blueprint:
  name: Light control with Tradfri remote
  description: |
    Turn On/Off several light with one Ikea Tradfri 5 button remote over ZHA
  domain: automation
  input:
    remote:
      name: Remote
      description: "IKEA 5 button remove to use"
      selector:
        device:
          integration: zha
          model: "TRADFRI remote control"
    light:
      name: Light
      description: Main Button
      default:
      selector:
        target:
          entity:
            domain: light
          
    light_up:
      name: Light
      description: Up Button
      default:
      selector:
        target:
          entity:
            domain: light
          
    light_down:
      name: Light
      description: Down Button
      default:
      selector:
        target:
          entity:
            domain: light
          
    light_left:
      name: Light
      description: Left Button
      default:
      selector:
        target:
          entity:
            domain: switch
          
    light_right:
      name: Light
      description: Right Button
      default:
      selector:
        target:
          entity:
            domain: light
          
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input remote
action:
- choose:
  - conditions:
    - '{{ trigger.event.data.command == "toggle" }}'
    sequence:
    - service: homeassistant.turn_on
      target: !input light
  - conditions:
    - '{{ trigger.event.data.command == "step_with_on_off" }}'
    sequence:
    - service: homeassistant.turn_on
      target: !input light_up
  - conditions:
    - '{{ trigger.event.data.command == "step" }}'
    sequence:
    - service: homeassistant.turn_on
      target: !input light_down
  - conditions:
    - '{{ trigger.event.data.command == "press" && trigger.event.data.args[0] === 257 }}'
    sequence:
    - service: homeassistant.turn_on
      target: !input light_left
  - conditions:
    - '{{ trigger.event.data.command == "press" && trigger.event.data.args[0] === 256 }}'
    sequence:
    - service: homeassistant.turn_on
      target: !input light_right
mode: restart
